export interface CurrencyInfo {
  code: string;
  symbol: string;
}

export const COUNTRY_CURRENCY: Record<string, CurrencyInfo> = {
  AU: { code: 'AUD', symbol: 'A$' },
  AT: { code: 'EUR', symbol: '€' },
  BE: { code: 'EUR', symbol: '€' },
  BR: { code: 'BRL', symbol: 'R$' },
  BG: { code: 'BGN', symbol: 'лв' },
  CA: { code: 'CAD', symbol: 'C$' },
  CL: { code: 'CLP', symbol: 'CL$' },
  CN: { code: 'CNY', symbol: '¥' },
  CO: { code: 'COP', symbol: 'COL$' },
  HR: { code: 'EUR', symbol: '€' },
  CY: { code: 'EUR', symbol: '€' },
  CZ: { code: 'CZK', symbol: 'Kč' },
  DK: { code: 'DKK', symbol: 'kr' },
  EE: { code: 'EUR', symbol: '€' },
  FI: { code: 'EUR', symbol: '€' },
  FR: { code: 'EUR', symbol: '€' },
  DE: { code: 'EUR', symbol: '€' },
  GR: { code: 'EUR', symbol: '€' },
  HK: { code: 'HKD', symbol: 'HK$' },
  HU: { code: 'HUF', symbol: 'Ft' },
  IS: { code: 'ISK', symbol: 'kr' },
  IN: { code: 'INR', symbol: '₹' },
  ID: { code: 'IDR', symbol: 'Rp' },
  IE: { code: 'EUR', symbol: '€' },
  IL: { code: 'ILS', symbol: '₪' },
  IT: { code: 'EUR', symbol: '€' },
  JP: { code: 'JPY', symbol: '¥' },
  KR: { code: 'KRW', symbol: '₩' },
  LV: { code: 'EUR', symbol: '€' },
  LT: { code: 'EUR', symbol: '€' },
  LU: { code: 'EUR', symbol: '€' },
  MY: { code: 'MYR', symbol: 'RM' },
  MT: { code: 'EUR', symbol: '€' },
  MX: { code: 'MXN', symbol: 'MX$' },
  NL: { code: 'EUR', symbol: '€' },
  NZ: { code: 'NZD', symbol: 'NZ$' },
  NO: { code: 'NOK', symbol: 'kr' },
  PH: { code: 'PHP', symbol: '₱' },
  PL: { code: 'PLN', symbol: 'zł' },
  PT: { code: 'EUR', symbol: '€' },
  RO: { code: 'RON', symbol: 'lei' },
  SG: { code: 'SGD', symbol: 'S$' },
  SK: { code: 'EUR', symbol: '€' },
  SI: { code: 'EUR', symbol: '€' },
  ZA: { code: 'ZAR', symbol: 'R' },
  ES: { code: 'EUR', symbol: '€' },
  SE: { code: 'SEK', symbol: 'kr' },
  CH: { code: 'CHF', symbol: 'CHF' },
  TW: { code: 'TWD', symbol: 'NT$' },
  TH: { code: 'THB', symbol: '฿' },
  TR: { code: 'TRY', symbol: '₺' },
  UA: { code: 'UAH', symbol: '₴' },
  AE: { code: 'AED', symbol: 'د.إ' },
  GB: { code: 'GBP', symbol: '£' },
};
