export const TANSTACK_QUERY_KEYS = {
  GET_ORG_PERMISSIONS: 'get_org_permissions',
  GET_EVENT: 'get_event',
  GET_EVENTS: 'get_events',
  GET_EVENT_FOR_ORG_MEMBER: 'get_event_for_org_member',
  GET_ORG_EVENTS: 'get_org_events',
  SEARCH_PUBLIC_EVENTS: 'search_public_events',
  GET_EVENTS_CATEGORIES: 'get_events_categories',
  GET_ORG_EVENTS_COUNTERS: 'get_org_events_counters',
  GET_TALENT_LOCATION: 'get_talent_location',
  GET_ME: 'get_me',
  GET_EVENTS_SUB_CATEGORIES: 'get_events_sub_categories',
  GET_EVENTS_TAGS: 'get_events_tags',
  PLACES_AUTOCOMPLETE: 'places_autocomplete',
  PLACE_DETAILS: 'place_details',
  GET_FILE_URL: 'get_file_url',
  GET_USER_AVAILABILITY: 'get_user_availability',
  MY_CHATS: 'my_chats',
  GET_CHAT_MESSAGES: 'get_chat_messages',
  GET_CHAT_PARTICIPANTS: 'get_chat_participants',
} as const;
