import { COLORS, TYPOGRAPHY } from '@styles';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 32,
    paddingHorizontal: 4,
    position: 'relative',
    gap: 4,
  },
  containerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    position: 'relative',
    padding: 4,
  },
  scrollContent: {
    flexDirection: 'row',
    height: 32,
    borderRadius: 32,
    paddingHorizontal: 4,
    position: 'relative',
  },
  scrollContentPill: {
    flexDirection: 'row',
    height: 40,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    padding: 4,
    position: 'relative',
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 32,
    paddingHorizontal: 12,
    borderWidth: 1,
    justifyContent: 'center',
    minWidth: 80,
    zIndex: 2,
  },
  tabPill: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 32,
    paddingHorizontal: 16,
    justifyContent: 'center',
    minWidth: 80,
    zIndex: 2,
    borderWidth: 0,
  },
  firstTab: {
    borderTopLeftRadius: 32,
    borderBottomLeftRadius: 32,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  lastTab: {
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 32,
    borderBottomRightRadius: 32,
  },
  slidingIndicator: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    zIndex: 1,
  },
  slidingIndicatorPill: {
    position: 'absolute',
    top: 4,
    bottom: 4,
    borderRadius: 12,
    zIndex: 1,
  },
  tabText: {
    ...TYPOGRAPHY.bold_12,
  },
  badge: {
    height: 18,
    marginLeft: 8,
    paddingHorizontal: 5,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    ...TYPOGRAPHY.bold_12,
  },
  label: {
    ...TYPOGRAPHY.h4_mob,
    marginBottom: 16,
  },
  badgeLabel: {
    ...TYPOGRAPHY.regular_16,
    color: COLORS.grayscale_500,
  },
});
