import { COLORS } from '@styles';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginTop: -35,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'flex-end',
  },
  loadingContainer: {
    backgroundColor: COLORS.black_20,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
  },
  cameraContainer: {
    position: 'absolute',
    top: 8,
    right: 8,
    bottom: 0,
    width: 25,
    height: 25,
    backgroundColor: COLORS.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageWrapper: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4.16 },
    shadowOpacity: 0.25,
    shadowRadius: 10.4,
    elevation: 5,
  },
  image: {
    width: 148,
    height: 148,
    backgroundColor: COLORS.gray_bg,
    borderRadius: 20,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  unverifiedBadge: {
    height: 24,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: COLORS.main,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleBadge: {
    width: 32,
    height: 32,
    borderRadius: 100,
    backgroundColor: COLORS.green,
    position: 'absolute',
    right: 5,
    bottom: 29,
  },
  circleBadgeUnverified: {
    bottom: 5,
  },
  nameContainer: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    marginBottom: 8,
  },
  cnBadge: {
    width: 18,
    height: 12,
    borderWidth: 1,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  animatedHeaderContainer: {
    position: 'absolute',
    bottom: -120,
    zIndex: 100,
    width: '100%',
    paddingHorizontal: 20,
  },
});
